### ISSUE TITLE
Github Score

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-04-18/Alex_Green#1]
What terminal errors are displaying?

**Comment by alexkenta** [comment]
It was a TS2339 error. I fixed it, just haven't pushed the updated one yet. 

in my subscribe method, I had just user instead of (user:any = {}) =>

and I know I should really be more specific than "any".

**Comment by dojo-json** [comment]
Good to hear. And you are correct, you probably want to give stronger Types to your data.
