### ISSUE TITLE
Empty Subscription

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-04-18/Alex_Green#2]
https://github.com/CodingDojo-MEAN-04-18/Alex_Green/blob/291c1cc2ffe173e4c724eec7e49b421ee4296029/fullMean/anonymousNotesX/anonymousNotes/src/app/app.component.ts#L36 

Your `subscribe` does nothing, this is generally not a good idea. Consider, instead of requesting all notes from your server, adding the returned note to the already existing array of notes. 

I would also recommend creating a `class` or `interface` to describe the shape of your data. This allows you to import that information where needed and assign a `Note` type to a variable rather than `any`.

**Comment by alexkenta** [comment]
For the .subscribe(), I've attempted a few things. I originally tried to push into existing array, but it wouldn't update in real time, only on refresh. Of everything I've tried, this was the only way I could add the note and have it successfully update in realtime. So it seems in that sense that it is doing something? If I remove it, it doesn't add the note at all.
